const foods = [
  {
    name: "Aiyu Jelly",
    value: 9,
    boosts: ["Almond Tofu"],
    boostedBy: ["Meaty Lunchbox", "Seafood Soup"],
    updatedForLevel: 5,
    bonus: 13,
  },
  {
    name: "Almond Tofu",
    value: 8,
    boosts: [],
    boostedBy: ["Meaty Lunchbox", "Seafood Soup", "Aiyu Jelly"],
    updatedForLevel: 5,
    bonus: 12,
  },
  {
    name: "Beef Stroganoff",
    value: 16,
    boosts: ["Lime Mint Soda", "Cheese"],
    boostedBy: [],
    updatedForLevel: 5,
    bonus: 24,
  },
  {
    name: "Brown Rice Tea",
    value: 6,
    boosts: ["Sweet Rice Cake", "Sweet Bean Jelly"],
    boostedBy: [
      "Rice Ball",
      "Meaty Lunchbox",
      "Cutlet Sandwich",
      "Seafood Bowl",
      "Kamameshi",
      "Miso Soup",
    ],
    updatedForLevel: 5,
    bonus: 9,
  },

  {
    name: "Chiffon Cake",
    value: 12,
    boosts: [],
    boostedBy: ["Spring Water", "Coffee"],
    updatedForLevel: 5,
    bonus: 18,
  },
  {
    name: "Coconut Ice Cream",
    value: 13,
    boosts: [],
    boostedBy: ["Meaty Lunchbox", "Coffee", "Tropical Fruit Juice", "Sandwich"],
    updatedForLevel: 5,
    bonus: 19,
  },
  {
    name: "Coffee",
    value: 6,
    boosts: [
      "Soft-Serve",
      "Maritozzi",
      "Gourmet Chocolate",
      "Fancy Cake",
      "Coconut Ice Cream",
      "Crepe",
      "Chiffon Cake",
      "Macaron",
    ],
    boostedBy: ["Cutlet Sandwich", "Sandwich"],
    updatedForLevel: 5,
    bonus: 9,
  },
  {
    name: "Cola",
    value: 6,
    boosts: [],
    boostedBy: ["Hamburger", "One-Pound Steak"],
    updatedForLevel: 5,
    bonus: 9,
  },
  {
    name: "Crepe",
    value: 13,
    boosts: ["Cheese"],
    boostedBy: ["Coffee", "Soft-Serve", "Gourmet Chocolate"],
    updatedForLevel: 5,
    bonus: 19,
  },
  {
    name: "Cutlet Sandwich",
    value: 13,
    boosts: ["Brown Rice Tea", "Coffee", "Ginger Ale", "Cheese"],
    boostedBy: [],
    updatedForLevel: 5,
    bonus: 19,
  },
  {
    name: "Energy Drink",
    value: 11,
    boosts: ["Lime Mint Soda"],
    boostedBy: ["Hamburger"],
    updatedForLevel: 5,
    bonus: 16,
  },
  {
    name: "Fancy Cake",
    value: 15,
    boosts: [],
    boostedBy: [
      "Coffee",
      "Tropical Fruit Juice",
      "Lime Mint Soda",
      "Grape Juice",
    ],
    updatedForLevel: 5,
    bonus: 22,
  },
  {
    name: "Ginger Ale",
    value: 12,
    boosts: ["Cheese"],
    boostedBy: [
      "Ramen",
      "Meaty Lunchbox",
      "Cutlet Sandwich",
      "Hamburger",
      "Seafood Bowl",
    ],
    updatedForLevel: 5,
    bonus: 18,
  },
  {
    name: "Gourmet Chocolate",
    value: 15,
    boosts: ["Crepe", "Macaron"],
    boostedBy: ["Coffee", "Lime Mint Soda", "Grape Juice"],
    updatedForLevel: 5,
    bonus: 22,
  },
  {
    name: "Grape Juice",
    value: 15,
    boosts: ["Gourmet Chocolate", "Fancy Cake", "Cheese"],
    boostedBy: ["One-Pound Steak"],
    updatedForLevel: 5,
    bonus: 22,
  },
  {
    name: "Cheese",
    value: 11,
    boosts: [
    ],
    boostedBy: [
      "Cutlet Sandwich",
      "Hamburger",
      "Beef Stroganoff",
      "One-Pound Steak",
      "Sandwich",
      "Ginger Ale",
      "Lime Mint Soda",
      "Grape Juice",
      "Crepe",
    ],
    updatedForLevel: 5,
    bonus: 16,
  },
  {
    name: "Hamburger",
    value: 13,
    boosts: ["Cola", "Energy Drink", "Ginger Ale", "Cheese"],
    boostedBy: [],
    updatedForLevel: 5,
    bonus: 19,
  },
  {
    name: "Kamameshi",
    value: 15,
    boosts: [
      "Miso Soup",
      "Spring Water",
      "Brown Rice Tea",
      "Sweet Rice Cake",
      "Sweet Bean Jelly",
    ],
    boostedBy: [],
    updatedForLevel: 5,
    bonus: 22,
  },
  {
    name: "Lime Mint Soda",
    value: 13,
    boosts: ["Gourmet Chocolate", "Fancy Cake", "Cheese"],
    boostedBy: ["Beef Stroganoff", "Energy Drink"],
    updatedForLevel: 5,
    bonus: 19,
  },
  {
    name: "Macaron",
    value: 11,
    boosts: [],
    boostedBy: ["Coffee", "Tropical Fruit Juice", "Gourmet Chocolate"],
    updatedForLevel: 5,
    bonus: 16,
  },
  {
    name: "Maritozzi",
    value: 12,
    boosts: [],
    boostedBy: ["Coffee", "Soft-Serve"],
    updatedForLevel: 5,
    bonus: 18,
  },
  {
    name: "Meaty Lunchbox",
    value: 11,
    boosts: [
      "Miso Soup",
      "Brown Rice Tea",
      "Ginger Ale",
      "Aiyu Jelly",
      "Coconut Ice Cream",
      "Almond Tofu",
    ],
    boostedBy: [],
    updatedForLevel: 5,
    bonus: 16,
  },
  {
    name: "Miso Soup",
    value: 8,
    boosts: ["Brown Rice Tea"],
    boostedBy: ["Rice Ball", "Meaty Lunchbox", "Seafood Bowl", "Kamameshi"],
    updatedForLevel: 5,
    bonus: 12,
  },
  {
    name: "Molokheya Soup",
    value: 13,
    boosts: [],
    boostedBy: ["One-Pound Steak", "Sandwich"],
    updatedForLevel: 5,
    bonus: 19,
  },
  {
    name: "One-Pound Steak",
    value: 19,
    boosts: ["Seafood Soup", "Molokheya Soup", "Cola", "Grape Juice", "Cheese"],
    boostedBy: [],
    updatedForLevel: 5,
    bonus: 28,
  },
  {
    name: "Ramen",
    value: 8,
    boosts: ["Seafood Soup", "Spring Water", "Ginger Ale"],
    boostedBy: [],
    updatedForLevel: 5,
    bonus: 12,
  },
  {
    name: "Rice Ball",
    value: 6,
    boosts: ["Miso Soup", "Spring Water", "Brown Rice Tea"],
    boostedBy: [],
    updatedForLevel: 5,
    bonus: 9,
  },
  {
    name: "Sandwich",
    value: 6,
    boosts: ["Molokheya Soup", "Coffee", "Coconut Ice Cream", "Cheese"],
    boostedBy: [],
    updatedForLevel: 5,
    bonus: 9,
  },
  {
    name: "Seafood Bowl",
    value: 16,
    boosts: ["Miso Soup", "Seafood Soup", "Brown Rice Tea", "Ginger Ale"],
    boostedBy: [],
    updatedForLevel: 5,
    bonus: 24,
  },
  {
    name: "Seafood Soup",
    value: 13,
    boosts: ["Aiyu Jelly", "Almond Tofu"],
    boostedBy: ["Ramen", "Seafood Bowl", "One-Pound Steak"],
    updatedForLevel: 5,
    bonus: 19,
  },
  {
    name: "Soft-Serve",
    value: 9,
    boosts: ["Maritozzi", "Crepe"],
    boostedBy: ["Coffee"],
    updatedForLevel: 5,
    bonus: 13,
  },
  {
    name: "Spring Water",
    value: 5,
    boosts: ["Chiffon Cake"],
    boostedBy: ["Rice Ball", "Ramen", "Kamameshi"],
    updatedForLevel: 5,
    bonus: 7,
  },
  {
    name: "Sweet Bean Jelly",
    value: 8,
    boosts: [],
    boostedBy: ["Kamameshi", "Brown Rice Tea", "Sweet Rice Cake"],
    updatedForLevel: 5,
    bonus: 12,
  },
  {
    name: "Sweet Rice Cake",
    value: 6,
    boosts: ["Sweet Bean Jelly"],
    boostedBy: ["Kamameshi", "Brown Rice Tea"],
    updatedForLevel: 5,
    bonus: 9,
  },
  {
    name: "Takoyaki",
    value: 8,
    boosts: [],
    boostedBy: [],
    updatedForLevel: 5,
    bonus: 12,
  },
  {
    name: "Tropical Fruit Juice",
    value: 13,
    boosts: ["Fancy Cake", "Coconut Ice Cream", "Macaron"],
    boostedBy: [],
    updatedForLevel: 5,
    bonus: 19,
  },
  {
    name: "Kairo Pudding",
    value: 27,
    boosts: [],
    boostedBy: [],
    updatedForLevel: 5,
    bonus: 40,
  },
];
